 # NumPY

NumPy is a powerful numerical computing library in Python that provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions. It is widely used in various fields for numerical computations and is an essential tool for any data scientist or researcher working with numerical data in Python.

In [99]:
import numpy as np
import time

In [100]:
data = np.random.rand(110000000)
print(data)

[0.05894083 0.96308218 0.6139025  ... 0.34250341 0.00745742 0.86995452]


Show time difference between list and numpy

In [101]:
# List

start = time.time()
mean_list = sum(data) / len(data)
print(time.time() - start)

11.652165412902832


In [102]:
# Numpy

start = time.time()
mean_np = np.mean(data)
print(time.time() - start)

0.18151330947875977


In [103]:
mean_list

0.5000077944121428

In [104]:
mean_np

0.5000077944119599

---

## Creating ndarrays


<a href="https://ibb.co/LYqp1wp"><img src="https://i.ibb.co/HBMgqvg/Screenshot-2023-04-15-125315.png" alt="Screenshot-2023-04-15-125315" border="0"></a>

In [105]:
# syntax
# arr = np.array()
# arr

In [106]:
# 0D (zero dimensional)
arr0 = np.array(1)

In [107]:
# 1D (one dimensional)
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [108]:
# 2D (2 dimensional)
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [109]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [110]:
# 3D (3 dimensional)
arr3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]

        ]
    ]
)

In [111]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [112]:
type(arr3)

numpy.ndarray

### Ndim
It Return a dimension of the array
has two dimensions with shape
inferred from the data. We can confirm this by inspecting the ndim and shape
attributes:

In [113]:
# 0D (zero dimensional)
arr0 = np.array(1)

In [114]:
arr0.ndim

0

In [115]:
# 1D (one dimensional)
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [116]:
arr.ndim

1

In [117]:
# 2D (2 dimensional)
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


In [118]:
arr2.ndim

2

In [119]:
# 3D (3 dimensional)
arr3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]

        ]
    ]
)

In [120]:
arr3.ndim

3

In [121]:
arr10 = np.array([1, 2, 3, 4], ndmin=10)


In [122]:
arr10.ndim

10

In [123]:
arr10

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

### Shape
It tails the shape of the array


In [124]:
arr3.shape

(2, 2, 3)

In [125]:
arr10.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)

In [126]:
arr2.shape

(2, 5)

## Data Types of ndarrays

<a href="https://ibb.co/Kmt7wfK"><img src="https://i.ibb.co/JCY2QG3/Screenshot-2023-04-15-125904.png" alt="Screenshot-2023-04-15-125904" border="0"></a>

### Type --- dtype
It tells about the type of the data

In [127]:
arr3.dtype

dtype('int32')

In [128]:
arrs = np.array(['a', 'b'])
arrs.dtype

dtype('<U1')

In [129]:
arr1 = np.array([1, 2, 3], dtype=np.float64)


In [130]:
arr1.dtype

dtype('float64')

Change the dtype of the data

In [131]:
arr1.astype(np.int32)

array([1, 2, 3])

### Size - it tells total number of element

In [132]:
arr1.size

3

In [133]:
arr2.size

10

In [134]:
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [135]:
#### 1 for the column
# 0  for the row

np.size(arr2, 1)


5

### Itemsize
It tells about the length of the single element in bytes

In [136]:
arr2.itemsize

4

### nbytes
Total bytes

In [137]:
arr2.nbytes

40

## Create array using arange method


In [138]:

aranged_array = np.arange(10)
aranged_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
aranged_array2 = np.arange(2, 10)  ## craete a 1D array with start with 2 and end with 9
aranged_array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
aranged_array3 = np.arange(2, 10, 2)  # create 1D ndarray with start with 2 and end with 9 and increment 2
aranged_array3

array([2, 4, 6, 8])

In [141]:
aranged_array4 = np.arange(1, 2, 0.1)

aranged_array4

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

## create a ndarray using zeros()

In [142]:
## zeros(shape, dtype)


zero_arr = np.zeros(2, dtype=int)
zero_arr

array([0, 0])

In [143]:
zero_arr = np.zeros([3, 5], dtype=int)
zero_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# CRUD Operations

## Create a ndarray

In [144]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [145]:
arr.ndim

2

In [146]:
arr0 = np.zeros((3, 3))


In [147]:
arr0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [148]:
arr0 = np.zeros(10)

In [149]:
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [150]:
arr0 = np.zeros([2, 3, 4])


In [151]:
arr0

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [152]:
arr1 = np.ones([3, 4])

In [153]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [154]:
arre = np.empty([3, 4])

In [155]:
arre

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [156]:
arr = np.full([3, 4], 10)

In [157]:
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [158]:
arre = np.eye(3)

In [159]:
arre

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [160]:
arrd = np.diag([1, 2, 3, 4])


In [161]:
arrd

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [162]:
arr = np.linspace(0, 10, 20)

In [163]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [164]:
arrr = np.random.rand(10)


In [165]:
arrr

array([0.03496459, 0.98420784, 0.35630444, 0.21286293, 0.67394507,
       0.49595468, 0.6600219 , 0.41715387, 0.48192157, 0.87535705])

In [166]:
arrr = np.random.randint(15, 25, size=(2, 3))

In [167]:
arrr

array([[16, 17, 15],
       [21, 24, 20]])

In [168]:
arrr = np.arange(1, 12, 2)

In [169]:
arrr

array([ 1,  3,  5,  7,  9, 11])

## u -> Update

In [170]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8, ], [1, 3, 5, 7]])

In [171]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

### Indexing

In [172]:
arr1[4]

5

In [173]:
arr1[-1]

9

In [174]:
# arr2[row,column]
arr2[1, 3]

8

In [175]:
arr2[1, 3] = 20

In [176]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 20],
       [ 1,  3,  5,  7]])

### Slicing

In [177]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 20],
       [ 1,  3,  5,  7]])

In [178]:
arr2[1:]

array([[ 5,  6,  7, 20],
       [ 1,  3,  5,  7]])

In [179]:
#Quiz

arr = np.linspace(10, 500, 12).reshape([3, 4])

In [180]:
arr

array([[ 10.        ,  54.54545455,  99.09090909, 143.63636364],
       [188.18181818, 232.72727273, 277.27272727, 321.81818182],
       [366.36363636, 410.90909091, 455.45454545, 500.        ]])

In [181]:
arr = np.random.rand(63).reshape([7, 9])

In [182]:
arr

array([[0.41817731, 0.85569619, 0.93140754, 0.95017926, 0.20056407,
        0.05807796, 0.43394743, 0.05801099, 0.50797974],
       [0.83560349, 0.30410753, 0.86288296, 0.56680833, 0.42516465,
        0.56748796, 0.42923299, 0.97998683, 0.92894674],
       [0.23052716, 0.86298435, 0.56785169, 0.83338889, 0.2377688 ,
        0.29250808, 0.37717004, 0.0722319 , 0.65629412],
       [0.46758347, 0.542612  , 0.49933742, 0.38849382, 0.32552425,
        0.25088968, 0.53901341, 0.10025452, 0.8257326 ],
       [0.12162622, 0.66466405, 0.31809839, 0.14592201, 0.08930309,
        0.93611742, 0.73049091, 0.31127429, 0.21107574],
       [0.6687363 , 0.53350711, 0.47373119, 0.71957254, 0.22841479,
        0.93368799, 0.71565901, 0.93700217, 0.0271319 ],
       [0.21713083, 0.07105267, 0.37256918, 0.19037741, 0.78673448,
        0.29358646, 0.08255645, 0.31184943, 0.77907733]])