 # NumPY

NumPy is a powerful numerical computing library in Python that provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions. It is widely used in various fields for numerical computations and is an essential tool for any data scientist or researcher working with numerical data in Python.

In [1]:
import numpy as np
import time

In [2]:
data = np.random.rand(110000000)
print(data)

[0.2998799  0.84863029 0.7604804  ... 0.01284185 0.66201138 0.11122159]


Show time difference between list and numpy

In [3]:
# List

start = time.time()
mean_list = sum(data) / len(data)
print(time.time() - start)

12.520597457885742


In [4]:
# Numpy

start = time.time()
mean_np = np.mean(data)
print(time.time() - start)

0.1945493221282959


In [5]:
mean_list

0.500044338368927

In [6]:
mean_np

0.5000443383689682

---

## Creating ndarrays


<a href="https://ibb.co/LYqp1wp"><img src="https://i.ibb.co/HBMgqvg/Screenshot-2023-04-15-125315.png" alt="Screenshot-2023-04-15-125315" border="0"></a>

In [7]:
# syntax
# arr = np.array()
# arr

In [8]:
# 0D (zero dimensional)
arr0 = np.array(1)

In [9]:
# 1D (one dimensional)
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [10]:
# 2D (2 dimensional)
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [11]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
# 3D (3 dimensional)
arr3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]

        ]
    ]
)

In [13]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
type(arr3)

numpy.ndarray

### Ndim
It Return a dimension of the array
has two dimensions with shape
inferred from the data. We can confirm this by inspecting the ndim and shape
attributes:

In [15]:
# 0D (zero dimensional)
arr0 = np.array(1)

In [16]:
arr0.ndim

0

In [17]:
# 1D (one dimensional)
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [18]:
arr.ndim

1

In [19]:
# 2D (2 dimensional)
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


In [20]:
arr2.ndim

2

In [21]:
# 3D (3 dimensional)
arr3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]

        ]
    ]
)

In [22]:
arr3.ndim

3

In [23]:
arr10 = np.array([1, 2, 3, 4], ndmin=10)


In [24]:
arr10.ndim

10

In [25]:
arr10

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

### Shape
It tails the shape of the array


In [26]:
arr3.shape

(2, 2, 3)

In [27]:
arr10.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)

In [28]:
arr2.shape

(2, 5)

## Data Types of ndarrays

<a href="https://ibb.co/Kmt7wfK"><img src="https://i.ibb.co/JCY2QG3/Screenshot-2023-04-15-125904.png" alt="Screenshot-2023-04-15-125904" border="0"></a>

### Type --- dtype
It tells about the type of the data

In [29]:
arr3.dtype

dtype('int32')

In [30]:
arrs = np.array(['a', 'b'])
arrs.dtype

dtype('<U1')

In [31]:
arr1 = np.array([1, 2, 3], dtype=np.float64)


In [32]:
arr1.dtype

dtype('float64')

Change the dtype of the data

In [33]:
arr1.astype(np.int32)

array([1, 2, 3])

### Size - it tells total number of element

In [34]:
arr1.size

3

In [35]:
arr2.size

10

In [36]:
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
#### 1 for the column
# 0  for the row

np.size(arr2, 1)


5

### Itemsize
It tells about the length of the single element in bytes

In [38]:
arr2.itemsize

4

### nbytes
Total bytes

In [39]:
arr2.nbytes

40

## Create array using arange method


In [40]:

aranged_array = np.arange(10)
aranged_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
aranged_array2 = np.arange(2, 10)  ## craete a 1D array with start with 2 and end with 9
aranged_array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
aranged_array3 = np.arange(2, 10, 2)  # create 1D ndarray with start with 2 and end with 9 and increment 2
aranged_array3

array([2, 4, 6, 8])

In [43]:
aranged_array4 = np.arange(1, 2, 0.1)

aranged_array4

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

## create a ndarray using zeros()

In [44]:
## zeros(shape, dtype)


zero_arr = np.zeros(2, dtype=int)
zero_arr

array([0, 0])

In [45]:
zero_arr = np.zeros([3, 5], dtype=int)
zero_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])