In [1]:
#numpy
import numpy as np
import time

a = np.random.rand(10000000)
start = time.time()

men_list = np.mean(a)
print(time.time() - start)


0.00997304916381836


In [2]:
np.__version__

'1.24.2'

# initializing the numpy array

In [3]:
import numpy as np

# 0D (zero dimentional)
arr = np.array(2)


In [4]:
# 1d array
arr = np.array([1, 2, 3, 4, 5])

type(arr)

numpy.ndarray

In [5]:
# 2d array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# 3d array
arr = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [8, 7, 6, 5],
        [4, 3, 2, 1]
    ]
])
print(arr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[8 7 6 5]
  [4 3 2 1]]]


# ndim attribute- it will gonna return the dimention of the array

In [7]:
# 0D (zero dimentional)
arr = np.array(2)
arr.ndim

0

In [8]:
# 1d array
arr = np.array([1, 2, 3, 4, 5])

arr.ndim

1

In [9]:
arr = np.array([1, 2, 3, 4, 5], ndmin=10)
arr.ndim

10