# c- > create

In [1]:
import numpy as np

#np.zeros()

arr = np.zeros((3,3))
arr
#2D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
arr = np.zeros(10)
arr

#1D

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr = np.zeros([10,10])
#2D
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
arr = np.zeros({1,2,3})
arr

TypeError: 'set' object does not support indexing

In [6]:
arr = np.zeros([10,3,4])
#3D
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
# np.ones()

arr  = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr = np.ones([10,9])
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
arr = np.empty([12,32])
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [17]:
arr = np.full([4,5], 9)
arr

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [2]:
# np.eye() -> identity matrix

arr = np.eye(8)    # row and column are same in identity matrix
arr

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [3]:
# np.diag()   diagonal matrix

arr = np.diag([1,2,3,4,5,6,7])
arr

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [4]:
# np.lin space()    # equally distributed

arr = np.linspace(0,10,20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [5]:
# np.random()    ## take random value

arr = np.random.rand(10)
arr


array([0.71095779, 0.81002462, 0.71715126, 0.63031359, 0.50248372,
       0.30270822, 0.45127538, 0.00727545, 0.95641145, 0.6946246 ])

In [10]:
# np.random.randint()

arr = np.random.randint(15,50,size=(2,4))
arr

array([[17, 18, 17, 35],
       [18, 19, 18, 18]])

In [11]:
# np.arrange()

arr = np.arange(8)    # default start is zero and end is size-1
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
arr = np.arange(1,12,2)
arr

array([ 1,  3,  5,  7,  9, 11])

# u -> update

In [13]:
arr = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [14]:
# indexing
arr = np.array([1,2,3,4,5])

arr[-1]

5

In [5]:
arr = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])

# arr[2][3]
arr[2,3]

7

In [6]:
#slicing
arr[1:2]

array([[5, 6, 7, 8]])

In [7]:
#create a 3 x4 matrix, 10 ton 500 + elements should be eveniy distributed

arr= np.linspace(10,500,12)

arr.reshape(3,4)

arr

array([ 10.        ,  54.54545455,  99.09090909, 143.63636364,
       188.18181818, 232.72727273, 277.27272727, 321.81818182,
       366.36363636, 410.90909091, 455.45454545, 500.        ])

In [9]:
#create a 3 x4 matrix, 10 ton 500 + elements should be eveniy distributed

arr= np.linspace(10,500,13)

arr.reshape(3,4)

arr

ValueError: cannot reshape array of size 13 into shape (3,4)

In [10]:
# create a array 7 x 9 matrix where all element are random

arr = np.random.rand(63).reshape(7,9)
arr

array([[0.16692497, 0.686491  , 0.2464818 , 0.62387785, 0.17852603,
        0.67472219, 0.23639002, 0.68454766, 0.79030867],
       [0.06719675, 0.75784676, 0.1686486 , 0.61592203, 0.26547943,
        0.13977589, 0.70479137, 0.20889985, 0.25280365],
       [0.98138156, 0.78314475, 0.40954033, 0.41345964, 0.24456674,
        0.09525115, 0.26196137, 0.53395826, 0.14488694],
       [0.60974152, 0.05992666, 0.20892   , 0.59582519, 0.65446491,
        0.09165969, 0.40098225, 0.97234594, 0.59957516],
       [0.22046772, 0.54619433, 0.68492722, 0.9256601 , 0.64808045,
        0.06566829, 0.18833109, 0.22169866, 0.74726498],
       [0.76419101, 0.66650241, 0.41777366, 0.04527274, 0.90077923,
        0.14470064, 0.95812739, 0.04806971, 0.78854273],
       [0.12891253, 0.5776569 , 0.94862765, 0.92182751, 0.11936501,
        0.44611115, 0.70478619, 0.50723278, 0.22549397]])