<a href="https://colab.research.google.com/github/mihir210/python/blob/master/Numpy/3_Linear_Algebra_%26_Statistical_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematical function

In [2]:
import numpy as np


In [ ]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[10,9,8,7,6], [5,4,3,2,1]])


In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

* addition -> add two matrices or add an element to a matrix



In [ ]:
# adding two matrices

arr1 + arr2


array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [ ]:
# Adding an elemet

arr1 + 20


array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr3 = np.array([1,2])
arr3

array([1, 2])

In [ ]:
arr1  + arr3

ValueError: ignored

In [ ]:
arr3 = np.array([1,2,3,4,5])
arr3


In [ ]:
arr1 + arr3

ValueError: ignored

* Substraction

In [ ]:
arr1


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
arr1 + arr2

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [ ]:
arr1 - 30

array([[-29, -28, -27, -26, -25],
       [-24, -23, -22, -21, -20]])

* Division


In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
arr1/arr2

array([[ 0.1       ,  0.22222222,  0.375     ,  0.57142857,  0.83333333],
       [ 1.2       ,  1.75      ,  2.66666667,  4.5       , 10.        ]])

In [ ]:
arr1/arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr1/3

array([[0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
       [2.        , 2.33333333, 2.66666667, 3.        , 3.33333333]])

* Exponential


In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
arr1 ** arr2

array([[    1,   512,  6561, 16384, 15625],
       [ 7776,  2401,   512,    81,    10]])

In [ ]:
arr1 ** 3

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000]])

* Multiplication -> cross and dot product


In [ ]:
arr1


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
# cross product
arr1 * arr2

array([[10, 18, 24, 28, 30],
       [30, 28, 24, 18, 10]])

In [ ]:
# Dot product

# arr1 is 2 * 5 
# arr2 is 2 x 5
arr3 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])


In [ ]:
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.dot(arr1,arr3)

array([[ 95, 110],
       [220, 260]])

In [ ]:
np.matmul(arr1,arr3)

array([[ 95, 110],
       [220, 260]])

* Determinant

In [3]:
detarray = np.array([[-4,-10],[0,5]])
detarray

array([[ -4, -10],
       [  0,   5]])

In [8]:
# np.linalg.det(arr)

np.linalg.det(detarray)

-19.999999999999996

In [10]:
detarray1= np.array([[-4,-10,-6],[0,5,7],[-9,6,0]])
np.linalg.det(detarray1)

528.0

* inverse of matrix

In [11]:
arrinv  = np.array([[1,2],[3,4]])
arrinv

array([[1, 2],
       [3, 4]])

In [12]:
np.linalg.inv(arrinv)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [13]:
np.linalg.det(arrinv)

-2.0000000000000004

In [14]:
# Adjoint of the matrix
arrinv.transpose()

array([[1, 3],
       [2, 4]])

# statistics


In [14]:
statarr = np.array([[20,30,-40],[0,10,-1],[7,6,34]])
statarr

array([[ 20,  30, -40],
       [  0,  10,  -1],
       [  7,   6,  34]])

* max()

In [22]:
np.max(statarr)

34

In [23]:
np.max(statarr, axis=0)    # axis =0 is the column

array([20, 30, 34])

In [24]:
np.max(statarr,axis=1)    # axis = 1 is row


array([30, 10, 34])

In [25]:
np.min(statarr)

-40

In [26]:
np.min(statarr, axis=0)

array([  0,   6, -40])

* Sum

In [27]:
np.sum(statarr)

66

In [28]:
np.sum(statarr, axis=0)

array([27, 46, -7])

In [29]:
np.sum(statarr, axis=1)

array([10,  9, 47])

* argmax
    index of max element


In [30]:
np.argmax(statarr)

8

In [31]:
np.argmin(statarr)

2

* around()

In [4]:
arr = np.array([0.46,0.98])

np.around(arr)

array([0., 1.])

In [5]:
np.around(arr, decimals=1)

array([0.5, 1. ])

* floor & ceil

In [6]:
a = np.array([-1.7,-4.2,4.6,-0.87])
np.floor(a)

array([-2., -5.,  4., -1.])

In [7]:
np.ceil(a)

array([-1., -4.,  5., -0.])

* copy & view

In [9]:
x = arr.copy()
x

array([0.46, 0.98])

In [11]:
# view is reference

x = arr.view()
x

array([0.46, 0.98])

* iteration

In [12]:
for i in arr:
    print(i)

0.46
0.98


In [17]:
for i in statarr:
    for j in i:
        print(j)

20
30
-40
0
10
-1
7
6
34


In [18]:
for i in np.nditer(statarr):
    print(i)

20
30
-40
0
10
-1
7
6
34
