In [2]:
import  numpy as np


In [2]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])


# Staking


In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [7]:
# hstack() >>> horizontal stack
# vstack()

np.vstack((arr1,arr2))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [9]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [10]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [11]:
np.dstack((arr1,arr2))

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15],
        [ 6, 16]]])

In [13]:
b = np.array_split(arr1,3)
b

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [14]:
b[0]

array([[1, 2, 3]])

In [15]:
b[0][0]

array([1, 2, 3])

In [16]:
b[0][0][0]

1

# searching

In [17]:
# where
arr3 = np.array([1,2,3,4,5,6])
np.where(arr3==4)

(array([3], dtype=int64),)

In [18]:
np.where(arr3>4)

(array([4, 5], dtype=int64),)

# sorting


In [3]:
arr3 = np.array([10,5,6,-10,-7,20,0,4,4.5,18])


In [4]:
arr3

array([ 10. ,   5. ,   6. , -10. ,  -7. ,  20. ,   0. ,   4. ,   4.5,
        18. ])

In [5]:
np.sort(arr3)

array([-10. ,  -7. ,   0. ,   4. ,   4.5,   5. ,   6. ,  10. ,  18. ,
        20. ])

In [6]:
-np.sort(-arr3)

array([ 20. ,  18. ,  10. ,   6. ,   5. ,   4.5,   4. ,   0. ,  -7. ,
       -10. ])

# any() & all()

In [9]:
arr3 = np.array([2,4,6,8,9])


In [10]:
arr3

array([2, 4, 6, 8, 9])

In [12]:
np.any(arr3 % 2==0)


True

In [13]:
np.all(arr3 % 2==0)     # all value check

False

# arrange
# size

In [17]:
a = np.arange(12)

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [19]:
np.resize(a,(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [20]:
np.resize(a,(10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3]])

In [21]:
# delete (arr,obj,axis)

np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])